// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulesApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulesApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319195929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ModulesApp.Models.BackgroundServices.DbBackgroundService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigurationData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BackgroundService");
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.DbDashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IconString")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.DbDashboardEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DashboardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentEntityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("ParentEntityId");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ModulesApp.Models.DbAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BackgroundServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundServiceId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("ModulesApp.Models.DbModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Chip")
                        .HasColumnType("text");

                    b.Property<int>("CommInterval")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text");

                    b.Property<int?>("FlashSize")
                        .HasColumnType("integer");

                    b.Property<int?>("FreeHeap")
                        .HasColumnType("integer");

                    b.Property<string>("IDFVersion")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastResponse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.Property<int>("ProgramStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ProgramVersion")
                        .HasColumnType("text");

                    b.Property<string>("WifiPassword")
                        .HasColumnType("text");

                    b.Property<string>("WifiSsid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("ModulesApp.Models.ModulesPrograms.DbModuleFirmware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IdfVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModuleFirmware");
                });

            modelBuilder.Entity("ModulesApp.Models.ModulesPrograms.DbModuleProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FirmwareId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmwareId");

                    b.ToTable("ModuleProgram");
                });

            modelBuilder.Entity("ModulesApp.Models.ModulesPrograms.DbModuleProgramFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("ModuleProgramFile");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbGlobalValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GlobalValue");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BackgroundServiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DashboardEntityId")
                        .HasColumnType("bigint");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TriggerSourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundServiceId");

                    b.HasIndex("DashboardEntityId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTaskLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("SourceDataType")
                        .HasColumnType("integer");

                    b.Property<bool>("SourceInput")
                        .HasColumnType("boolean");

                    b.Property<long>("SourceNodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("SourcePositionAlignment")
                        .HasColumnType("integer");

                    b.Property<int>("TargetDataType")
                        .HasColumnType("integer");

                    b.Property<bool>("TargetInput")
                        .HasColumnType("boolean");

                    b.Property<long>("TargetNodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetPositionAlignment")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("TaskLink");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTaskNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BoolVal1")
                        .HasColumnType("boolean");

                    b.Property<bool>("BoolVal2")
                        .HasColumnType("boolean");

                    b.Property<double>("DoubleVal1")
                        .HasColumnType("double precision");

                    b.Property<double>("DoubleVal2")
                        .HasColumnType("double precision");

                    b.Property<int>("InputType")
                        .HasColumnType("integer");

                    b.Property<long>("LongVal1")
                        .HasColumnType("bigint");

                    b.Property<long>("LongVal2")
                        .HasColumnType("bigint");

                    b.Property<long>("LongVal3")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<string>("StringVal1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StringVal2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StringVal3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubType")
                        .HasColumnType("integer");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbAccumulationTankEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbButtonEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbDataListEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbFrameEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbKeyValueEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbLineChart24hEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbRoomsTempEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbSwitchEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbToggleGroupEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.Entities.DbValueSetterEntity", b =>
                {
                    b.HasBaseType("ModulesApp.Models.Dasboards.DbDashboardEntity");

                    b.ToTable("DashBoardEntity");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbArithmeticOperationNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbArithmeticSaturationNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(11);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbArrayOperationNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbBooleanOperationNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbBranchNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(12);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbConditionNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbConvertToNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbDataDisplayNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbDateTimeNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbFromAnyNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbFromMessageNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbGlobalValueNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(13);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbSendMessageNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.Nodes.DbValueNode", b =>
                {
                    b.HasBaseType("ModulesApp.Models.ServerTasks.DbTaskNode");

                    b.ToTable("TaskNode");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.DbDashboardEntity", b =>
                {
                    b.HasOne("ModulesApp.Models.Dasboards.DbDashboard", "Dashboard")
                        .WithMany("Entities")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModulesApp.Models.Dasboards.DbDashboardEntity", null)
                        .WithMany("ChildEntities")
                        .HasForeignKey("ParentEntityId");

                    b.Navigation("Dashboard");
                });

            modelBuilder.Entity("ModulesApp.Models.DbAction", b =>
                {
                    b.HasOne("ModulesApp.Models.BackgroundServices.DbBackgroundService", "BackgroundService")
                        .WithMany("Actions")
                        .HasForeignKey("BackgroundServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ModulesApp.Models.DbModule", "Module")
                        .WithMany("Actions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BackgroundService");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ModulesApp.Models.ModulesPrograms.DbModuleProgram", b =>
                {
                    b.HasOne("ModulesApp.Models.ModulesPrograms.DbModuleFirmware", "Firmware")
                        .WithMany()
                        .HasForeignKey("FirmwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firmware");
                });

            modelBuilder.Entity("ModulesApp.Models.ModulesPrograms.DbModuleProgramFile", b =>
                {
                    b.HasOne("ModulesApp.Models.ModulesPrograms.DbModuleProgram", "Program")
                        .WithMany("Files")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTask", b =>
                {
                    b.HasOne("ModulesApp.Models.BackgroundServices.DbBackgroundService", "BackgroundService")
                        .WithMany("ServerTasks")
                        .HasForeignKey("BackgroundServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModulesApp.Models.Dasboards.DbDashboardEntity", "DashboardEntity")
                        .WithMany("ServerTasks")
                        .HasForeignKey("DashboardEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModulesApp.Models.DbModule", "Module")
                        .WithMany("ServerTasks")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BackgroundService");

                    b.Navigation("DashboardEntity");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTaskLink", b =>
                {
                    b.HasOne("ModulesApp.Models.ServerTasks.DbTaskNode", "Source")
                        .WithMany("SourceLinks")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModulesApp.Models.ServerTasks.DbTaskNode", "Target")
                        .WithMany("TargetLinks")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTaskNode", b =>
                {
                    b.HasOne("ModulesApp.Models.ServerTasks.DbTask", "Task")
                        .WithMany("Nodes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ModulesApp.Models.BackgroundServices.DbBackgroundService", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("ServerTasks");
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.DbDashboard", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("ModulesApp.Models.Dasboards.DbDashboardEntity", b =>
                {
                    b.Navigation("ChildEntities");

                    b.Navigation("ServerTasks");
                });

            modelBuilder.Entity("ModulesApp.Models.DbModule", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("ServerTasks");
                });

            modelBuilder.Entity("ModulesApp.Models.ModulesPrograms.DbModuleProgram", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTask", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("ModulesApp.Models.ServerTasks.DbTaskNode", b =>
                {
                    b.Navigation("SourceLinks");

                    b.Navigation("TargetLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
